server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8

druid:
  type: com.alibaba.druid.pool.DruidDataSource
  # 主数据源
  master:
    url: jdbc:mysql://localhost:3306/bgis1?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    initialSize: 5
    # 最小空闲，最大空闲已废弃
    minIdle: 1
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 池化的配置
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # druid监控配置
    filters: stat,wall,slf4j
    useGlobalDataSourceStat: true
  # 从数据源
  slave1:
    url: jdbc:mysql://localhost:3306/bgis2?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    initialSize: 5
    minIdle: 1
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    useGlobalDataSourceStat: true

mybatis:
  mapper-locations: classpath:/com/stefan/sbt/dao/demo/*.xml